import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import test from "node:test";

// Directories whose .js and .css files are uploaded to Cloudflare Pages and so
// cost real bytes on every deploy. static/ is excluded here because it is
// covered by its own module contracts; this guard is about the legacy js/ and
// css/ roots, where three byte-identical copies of a superseded terminal card
// accumulated unnoticed.
const SHIPPED_ROOTS = ["js", "css"];
const SHIPPED_EXTENSIONS = new Set([".js", ".css", ".mjs"]);

// Assets that are intentionally present without an inbound reference. Add an
// entry only with a reason; an empty list is the healthy state.
const ALLOWED_UNREFERENCED = new Set([]);

function walk(directory) {
  const found = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const full = path.posix.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "tests" || entry.name === "node_modules") continue;
      found.push(...walk(full));
      continue;
    }
    if (SHIPPED_EXTENSIONS.has(path.extname(entry.name))) found.push(full);
  }
  return found;
}

function shippedAssets() {
  return SHIPPED_ROOTS.filter((root) => existsSync(root)).flatMap(walk);
}

function corpus(shipped) {
  const shippedSet = new Set(shipped);
  const readable = new Set([".html", ".js", ".mjs", ".json", ".yml", ".css", ".md"]);
  const parts = [];

  function collect(directory) {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const full = path.posix.join(directory, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "node_modules" || entry.name === ".git") continue;
        collect(full);
        continue;
      }
      if (!readable.has(path.extname(entry.name))) continue;
      // A file cannot justify its own existence, and neither can a sibling
      // copy of the same dead module, so shipped assets are not part of the
      // reference corpus.
      if (shippedSet.has(full)) continue;
      parts.push(readFileSync(full, "utf8"));
    }
  }

  collect(".");
  return parts.join("\n");
}

test("no shipped js or css asset is unreferenced", () => {
  const shipped = shippedAssets();
  assert.ok(shipped.length > 0, "expected to find shipped assets");

  const text = corpus(shipped);
  const orphans = shipped.filter(
    (asset) => !ALLOWED_UNREFERENCED.has(asset) && !text.includes(path.basename(asset)),
  );

  assert.deepEqual(
    orphans,
    [],
    `these assets ship to production but nothing loads them: ${orphans.join(", ")}`,
  );
});

test("no two shipped assets have identical content", () => {
  const byDigest = new Map();
  const duplicates = [];

  for (const asset of shippedAssets()) {
    const digest = createHash("sha256").update(readFileSync(asset)).digest("hex");
    const first = byDigest.get(digest);
    if (first) duplicates.push(`${first} == ${asset}`);
    else byDigest.set(digest, asset);
  }

  assert.deepEqual(
    duplicates,
    [],
    `superseded copies still ship: ${duplicates.join(", ")}`,
  );
});

test("the publish exclusion list has no entries for deleted files", () => {
  // Excluding a file from the Pages upload is not the same as removing it.
  // llms.tsx survived as a byte-identical duplicate of llms.txt for exactly
  // this reason: it was added to .pagesignore instead of being deleted.
  // Only anchored file entries are checked. Directory entries such as
  // /node_modules/ and /.wrangler/ are generated by tooling and are correctly
  // absent from a clean checkout.
  const stale = readFileSync(".pagesignore", "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .filter((line) => line.startsWith("/") && !line.endsWith("/"))
    .map((line) => line.replace(/^\/+/, ""))
    .filter((entry) => !existsSync(entry));

  assert.deepEqual(
    stale,
    [],
    `.pagesignore excludes paths that no longer exist: ${stale.join(", ")}`,
  );
});

test("the web app manifest declares the fields required to install", () => {
  const manifest = JSON.parse(readFileSync("site.webmanifest", "utf8"));
  for (const field of ["id", "name", "short_name", "start_url", "scope", "display"]) {
    assert.ok(manifest[field], `site.webmanifest is missing ${field}`);
  }
  assert.ok(Array.isArray(manifest.icons) && manifest.icons.length > 0, "icons must be declared");
});

test("the Lab shell no longer injects a generic social card at runtime", () => {
  // scripts/og/verify.mjs fails the build when a page references
  // og-default.png, but it reads static HTML and cannot see metadata written
  // by JavaScript. Every Lab route now declares its own card, so the runtime
  // fallback was unreachable and hid that gap from the gate.
  const shell = readFileSync("lab/shared/shell.js", "utf8");
  assert.ok(!shell.includes("og-default"), "the runtime og-default fallback is a verifier blind spot");
});
